//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace TW.Nfe {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeCancelamento2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2")]
    public partial class NfeCancelamento2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg nfeCabecMsgValueField;
        
        private System.Threading.SendOrPostCallback nfeCancelamentoNF2OperationCompleted;
        
        /// <remarks/>
        public NfeCancelamento2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeCancelamento2.asmx";
        }
        
        public nfeCabecMsg nfeCabecMsgValue {
            get {
                return this.nfeCabecMsgValueField;
            }
            set {
                this.nfeCabecMsgValueField = value;
            }
        }
        
        /// <remarks/>
        public event nfeCancelamentoNF2CompletedEventHandler nfeCancelamentoNF2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsgValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2/nfeCancelamentoNF2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2")]
        public System.Xml.XmlNode nfeCancelamentoNF2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeCancelamentoNF2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeCancelamentoNF2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeCancelamentoNF2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeCancelamentoNF2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeCancelamentoNF2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCancelamentoNF2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeCancelamentoNF2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeCancelamentoNF2OperationCompleted == null)) {
                this.nfeCancelamentoNF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeCancelamentoNF2OperationCompleted);
            }
            this.InvokeAsync("nfeCancelamentoNF2", new object[] {
                        nfeDadosMsg}, this.nfeCancelamentoNF2OperationCompleted, userState);
        }
        
        private void OnnfeCancelamentoNF2OperationCompleted(object arg) {
            if ((this.nfeCancelamentoNF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeCancelamentoNF2Completed(this, new nfeCancelamentoNF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeCancelamento2", IsNullable=false)]
    public partial class nfeCabecMsg : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeCancelamentoNF2CompletedEventHandler(object sender, nfeCancelamentoNF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeCancelamentoNF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeCancelamentoNF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeConsulta2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2")]
    public partial class NfeConsulta2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg1 nfeCabecMsgField;
        
        private System.Threading.SendOrPostCallback nfeConsultaNF2OperationCompleted;
        
        /// <remarks/>
        public NfeConsulta2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeConsulta2.asmx";
        }
        
        public nfeCabecMsg1 nfeCabecMsg {
            get {
                return this.nfeCabecMsgField;
            }
            set {
                this.nfeCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        public event nfeConsultaNF2CompletedEventHandler nfeConsultaNF2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsg", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2/nfeConsultaNF2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2")]
        public System.Xml.XmlNode nfeConsultaNF2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeConsultaNF2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeConsultaNF2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeConsultaNF2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeConsultaNF2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeConsultaNF2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeConsultaNF2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeConsultaNF2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeConsultaNF2OperationCompleted == null)) {
                this.nfeConsultaNF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeConsultaNF2OperationCompleted);
            }
            this.InvokeAsync("nfeConsultaNF2", new object[] {
                        nfeDadosMsg}, this.nfeConsultaNF2OperationCompleted, userState);
        }
        
        private void OnnfeConsultaNF2OperationCompleted(object arg) {
            if ((this.nfeConsultaNF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeConsultaNF2Completed(this, new nfeConsultaNF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2")]
    [System.Xml.Serialization.XmlRootAttribute("nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", IsNullable=false)]
    public partial class nfeCabecMsg1 : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeConsultaNF2CompletedEventHandler(object sender, nfeConsultaNF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeConsultaNF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeConsultaNF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeInutilizacao2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2")]
    public partial class NfeInutilizacao2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg2 nfeCabecMsgField;
        
        private System.Threading.SendOrPostCallback nfeInutilizacaoNF2OperationCompleted;
        
        /// <remarks/>
        public NfeInutilizacao2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeInutilizacao2.asmx";
        }
        
        public nfeCabecMsg2 nfeCabecMsg {
            get {
                return this.nfeCabecMsgField;
            }
            set {
                this.nfeCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        public event nfeInutilizacaoNF2CompletedEventHandler nfeInutilizacaoNF2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsg", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2/nfeInutilizacaoNF2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2")]
        public System.Xml.XmlNode nfeInutilizacaoNF2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeInutilizacaoNF2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeInutilizacaoNF2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeInutilizacaoNF2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeInutilizacaoNF2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeInutilizacaoNF2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeInutilizacaoNF2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeInutilizacaoNF2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeInutilizacaoNF2OperationCompleted == null)) {
                this.nfeInutilizacaoNF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeInutilizacaoNF2OperationCompleted);
            }
            this.InvokeAsync("nfeInutilizacaoNF2", new object[] {
                        nfeDadosMsg}, this.nfeInutilizacaoNF2OperationCompleted, userState);
        }
        
        private void OnnfeInutilizacaoNF2OperationCompleted(object arg) {
            if ((this.nfeInutilizacaoNF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeInutilizacaoNF2Completed(this, new nfeInutilizacaoNF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2")]
    [System.Xml.Serialization.XmlRootAttribute("nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2", IsNullable=false)]
    public partial class nfeCabecMsg2 : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeInutilizacaoNF2CompletedEventHandler(object sender, nfeInutilizacaoNF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeInutilizacaoNF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeInutilizacaoNF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeRecepcao2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2")]
    public partial class NfeRecepcao2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg3 nfeCabecMsgField;
        
        private System.Threading.SendOrPostCallback nfeRecepcaoLote2OperationCompleted;
        
        /// <remarks/>
        public NfeRecepcao2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx";
        }
        
        public nfeCabecMsg3 nfeCabecMsg {
            get {
                return this.nfeCabecMsgField;
            }
            set {
                this.nfeCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        public event nfeRecepcaoLote2CompletedEventHandler nfeRecepcaoLote2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsg", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2/nfeRecepcaoLote2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2")]
        public System.Xml.XmlNode nfeRecepcaoLote2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeRecepcaoLote2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeRecepcaoLote2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeRecepcaoLote2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeRecepcaoLote2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeRecepcaoLote2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeRecepcaoLote2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeRecepcaoLote2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeRecepcaoLote2OperationCompleted == null)) {
                this.nfeRecepcaoLote2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeRecepcaoLote2OperationCompleted);
            }
            this.InvokeAsync("nfeRecepcaoLote2", new object[] {
                        nfeDadosMsg}, this.nfeRecepcaoLote2OperationCompleted, userState);
        }
        
        private void OnnfeRecepcaoLote2OperationCompleted(object arg) {
            if ((this.nfeRecepcaoLote2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeRecepcaoLote2Completed(this, new nfeRecepcaoLote2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2")]
    [System.Xml.Serialization.XmlRootAttribute("nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRecepcao2", IsNullable=false)]
    public partial class nfeCabecMsg3 : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeRecepcaoLote2CompletedEventHandler(object sender, nfeRecepcaoLote2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeRecepcaoLote2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeRecepcaoLote2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeRetRecepcao2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")]
    public partial class NfeRetRecepcao2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg4 nfeCabecMsgField;
        
        private System.Threading.SendOrPostCallback nfeRetRecepcao2OperationCompleted;
        
        /// <remarks/>
        public NfeRetRecepcao2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeRetRecepcao2.asmx";
        }
        
        public nfeCabecMsg4 nfeCabecMsg {
            get {
                return this.nfeCabecMsgField;
            }
            set {
                this.nfeCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        public event nfeRetRecepcao2CompletedEventHandler nfeRetRecepcao2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsg", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2/nfeRetRecepcao2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")]
        public System.Xml.XmlNode nfeRetRecepcao2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeRetRecepcao2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeRetRecepcao2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeRetRecepcao2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeRetRecepcao2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeRetRecepcao2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeRetRecepcao2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeRetRecepcao2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeRetRecepcao2OperationCompleted == null)) {
                this.nfeRetRecepcao2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeRetRecepcao2OperationCompleted);
            }
            this.InvokeAsync("nfeRetRecepcao2", new object[] {
                        nfeDadosMsg}, this.nfeRetRecepcao2OperationCompleted, userState);
        }
        
        private void OnnfeRetRecepcao2OperationCompleted(object arg) {
            if ((this.nfeRetRecepcao2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeRetRecepcao2Completed(this, new nfeRetRecepcao2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2")]
    [System.Xml.Serialization.XmlRootAttribute("nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao2", IsNullable=false)]
    public partial class nfeCabecMsg4 : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeRetRecepcao2CompletedEventHandler(object sender, nfeRetRecepcao2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeRetRecepcao2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeRetRecepcao2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NfeStatusServico2Soap12", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")]
    public partial class NfeStatusServico2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private nfeCabecMsg5 nfeCabecMsgField;
        
        private System.Threading.SendOrPostCallback nfeStatusServicoNF2OperationCompleted;
        
        /// <remarks/>
        public NfeStatusServico2() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "https://nfe.fazenda.sp.gov.br/nfeweb/services/NfeStatusServico2.asmx";
        }
        
        public nfeCabecMsg5 nfeCabecMsg {
            get {
                return this.nfeCabecMsgField;
            }
            set {
                this.nfeCabecMsgField = value;
            }
        }
        
        /// <remarks/>
        public event nfeStatusServicoNF2CompletedEventHandler nfeStatusServicoNF2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("nfeCabecMsg", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2/nfeStatusServicoNF2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")]
        public System.Xml.XmlNode nfeStatusServicoNF2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")] System.Xml.XmlNode nfeDadosMsg) {
            object[] results = this.Invoke("nfeStatusServicoNF2", new object[] {
                        nfeDadosMsg});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnfeStatusServicoNF2(System.Xml.XmlNode nfeDadosMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nfeStatusServicoNF2", new object[] {
                        nfeDadosMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndnfeStatusServicoNF2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void nfeStatusServicoNF2Async(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeStatusServicoNF2Async(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void nfeStatusServicoNF2Async(System.Xml.XmlNode nfeDadosMsg, object userState) {
            if ((this.nfeStatusServicoNF2OperationCompleted == null)) {
                this.nfeStatusServicoNF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnfeStatusServicoNF2OperationCompleted);
            }
            this.InvokeAsync("nfeStatusServicoNF2", new object[] {
                        nfeDadosMsg}, this.nfeStatusServicoNF2OperationCompleted, userState);
        }
        
        private void OnnfeStatusServicoNF2OperationCompleted(object arg) {
            if ((this.nfeStatusServicoNF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nfeStatusServicoNF2Completed(this, new nfeStatusServicoNF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2")]
    [System.Xml.Serialization.XmlRootAttribute("nfeCabecMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", IsNullable=false)]
    public partial class nfeCabecMsg5 : System.Web.Services.Protocols.SoapHeader {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void nfeStatusServicoNF2CompletedEventHandler(object sender, nfeStatusServicoNF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nfeStatusServicoNF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nfeStatusServicoNF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}
